[project]
name = "AlphaZero_in_Pan"
version = "0.1.0"
description = "Using AlphaZero algorithm to play the game of Pan"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
]

[project.optional-dependencies]
ml = [
    "torch>=2.8.0",
]