learning_rate: 1.0e-4
weight_decay: 1.0e-4

batch_size: 32
batch_count: 8
epochs: 100

games_per_training: 1
num_simulations: 32
num_worlds: 4

c_puct_value: 1.0
policy_temp: 0.2

max_buffer_size: 1024

initial_max_game_length: 30
capped_max_game_length: 500
game_length_increment: 10

player_count: 4

save_dir: "checkpoints/"

wandb:
  entity: "reinforced-annealer"
  project: "pan-alpha-zero"
